name: Notify on mapdevicetypes.json changes
on:
  push:
    paths:
      - 'mapdevicetypes.json'

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Alert - mapdevicetypes.json was modified
          body: |
            Someone pushed changes to mapdevicetypes.json so you need to update DLLib's copy.

            Commit: ${{ github.event.head_commit.url }}
            Author: ${{ github.event.head_commit.author.name }}
            Message: ${{ github.event.head_commit.message }}
          to: rwinchester@siteworx.io
          from: MapDeviceTypes GitHub Actions
